index_name: "developer-quickstart-py"
data_path: "data/default"
system_prompt_template: |
  Instruction: Use the following pieces of context to answer the question at the end. Your answer should be a detailed and comprehensive synthesis of the provided context. Explain the key concepts and provide examples where possible.

  Context:
  {context}

  Question: {question}

  Answer:
